"use strict";

const { createDiscoreEmbed } = require("../../../lib/embedBuilder");
const { StringSelectMenuOptionBuilder } = require("discord.js");

const CATEGORIES = [
  {
    value: "overview",
    emoji: "🏠",
    label: "General Overview",
    description: "What Discore is & basic navigation",
  },
  {
    value: "scoreboards",
    emoji: "📊",
    label: "Scoreboards",
    description: "How scoreboards work",
  },
  {
    value: "merge",
    emoji: "🔀",
    label: "Merging Scoreboards",
    description: "Combine boards into totals boards",
  },
  {
    value: "archive",
    emoji: "🗄️",
    label: "Archives",
    description: "Browse, restore & manage archived boards",
  },
  {
    value: "moderation",
    emoji: "🛡️",
    label: "Moderation",
    description: "Mod commands, cases & appeals",
  },
  {
    value: "events",
    emoji: "🎮",
    label: "Events & Battles",
    description: "Events, battle signups & AI strategy",
  },
  {
    value: "players",
    emoji: "👤",
    label: "Players & Alliances",
    description: "Player profiles & alliances",
  },
  {
    value: "premium",
    emoji: "⭐",
    label: "Premium & Server Setup",
    description: "Plans, AI credits & server config",
  },
  {
    value: "xp",
    emoji: "✨",
    label: "XP & Leveling",
    description: "XP system, levels & leaderboards",
  },
  {
    value: "autoposts",
    emoji: "📣",
    label: "Auto Posts & Welcome",
    description: "Automated posts, welcome messages & placeholders",
  },
];

// ─── Embed builders ───────────────────────────────────────────────────────────

async function buildOverviewEmbed(interaction) {
  return createDiscoreEmbed(interaction, {
    title: "🏠 Discore V2 — General Overview",
    description: [
      "**Discore** is your all-in-one strategy-game command network.",
      "It provides scoreboards, events, battle signups, AI strategy, and player profiles — all from Discord.",
      "",
      "### ⚠️ Development Notice",
      "Discore V2 is **still in active development**. Commands, features, and behaviour may change as improvements roll out. If something doesn't work as expected, please report it to your server admins.",
      "",
      "### 🧭 Quick Navigation",
      "Use the dropdown below to switch between help categories:",
      "> 📊 **Scoreboards** — Create & manage scoreboards",
      "> 🔀 **Merging Scoreboards** — Combine boards into totals boards",
      "> 🗄️ **Archives** — Browse, restore & manage archived boards",
      "> 🛡️ **Moderation** — Warn, mute, ban, timeout & appeals",
      "> 🎮 **Events & Battles** — Schedule events, battle signups & AI strategy",
      "> 👤 **Players & Alliances** — Profiles & alliance management",
      "> ⭐ **Premium & Server Setup** — Plans, AI credits & configuration",
      "",
      "### 🔗 Core Commands",
      "`/scoreboard` · `/scores` · `/archive` · `/event` · `/ask` · `/unit`",
      "`/player` · `/suggestion` · `/mod` · `/automod` · `/role`",
      "`/server` · `/premium` · `/safecrack` · `/ping` · `/help` · `/xp`",
      "",
      "### 🎯 Supported Games",
      "Supremacy: WW3 • Conflict of Nations • Call of War • Supremacy 1914",
    ].join("\n"),
  });
}

async function buildScoreboardsEmbed(interaction) {
  return createDiscoreEmbed(interaction, {
    title: "📊 Scoreboards — Complete Guide",
    description: [
      "> ⚠️ This system is **in active development**. Behaviour described below may evolve.",
      "",
      "### 🔰 What Are Scoreboards?",
      "Scoreboards track wins/losses or points for **teams, players, or custom targets** across your server.",
      "",
      "They can track three target types:",
      "• **Users** — Individual Discord members",
      "• **Roles** — Entire Discord roles/teams",
      "• **Custom** — Any text name you want",
      "",
      "Scoreboards use one of two scoring systems:",
      "• **Win/Loss** — Tracks wins, losses, win streaks, and ratios",
      "• **Points** — Add or subtract point totals",
      "",
      "### 🏆 Scoreboard Control Centre",
      "Run **`/scoreboard`** to open the **Scoreboard Control Centre** — a premium interactive dashboard.",
      "",
      "**Dashboard buttons:**",
      "• **➕ Create Scoreboard** — Opens a modal to name and create a new board",
      "• **📊 Scores** — Links to `/scores @user` or `/scores @role`",
      "• **🔄 Refresh** — Reloads the dashboard",
      "• **❌ Close** — Closes the dashboard",
      "",
      "**Select a scoreboard** from the dropdown to open its **Board Control Panel**:",
      "",
      "### 🎛️ Board Control Panel",
      "After selecting a scoreboard, you get a dedicated control panel:",
      "",
      "**Score Type Dropdown** — Always visible at the top:",
      "• **Overall (no category)** — Default. Adds wins/losses without a category",
      "• **Score types you've created** — e.g. WW3 4X, WW3 1X, Apocalypse",
      "• Wins/losses added while a type is selected are tracked per-type on the same board",
      "",
      "**Target Selector:**",
      "• **User Select** — Pick a Discord user (for user-based boards)",
      "• **Role Select** — Pick a Discord role (for role/team boards)",
      "",
      "**Score Action Buttons:**",
      "• **🏆 +Win** — Add a win to the selected target and score type",
      "• **💀 +Loss** — Add a loss to the selected target and score type",
      "• **✏️ Points +/-** — Opens a modal to add/subtract points",
      "",
      "**Entry Management:**",
      "• **🧾 Edit** — Opens a modal with current wins/losses/points/streaks to edit",
      "• **🗑️ Delete** — Removes the selected target's entry from this board (with confirmation)",
      "",
      "**Board Management:**",
      "• **📢 Public** — Post the scoreboard to a channel (select any channel or thread)",
      "• **🔄 Refresh** — Reload the control panel",
      "• **🎨 Customize** — Set title, description, rename, theme colour, image, and score types",
      "• **🛠️ Advanced** — Repair live embed or delete the entire scoreboard",
      "• **⬅️ Back** — Return to the dashboard",
      "",
      "### 🎨 Customize Panel",
      "Click **🎨 Customize** to access:",
      "• **Set Title** — Change the live embed title",
      "• **Set Description** — Update season/info text",
      "• **Rename Board** — Change the internal board name",
      "• **Set Theme** — Change the embed colour (hex)",
      "• **Set Image** — Upload a PNG/JPG/WEBP thumbnail directly",
      "• **Remove Image** — Clear the current thumbnail",
      "• **🏷️ Add Score Type** — Create new game categories like WW3 4X, WW3 1X, Apocalypse",
      "",
      "### 📊 Quick Score Lookup",
      "**`/scores user:@User`** or **`/scores role:@Role`** — View a user or role's scores across all active and archived scoreboards.",
      "",
      "### 🔄 Category Views",
      "When a scoreboard has categories or merged sources, you can switch views:",
      "• **All Scores Combined** — Merges matching targets across categories",
      "• **Show All Categories** — Lists each category separately",
      "• **Single Category** — View only one source board's scores",
      "",
      "### 🔀 Merging & 🗄️ Archiving",
      "See the **Merging Scoreboards** and **Archives** sections in the dropdown for full guides.",
    ].join("\n"),
  });
}

async function buildMergeEmbed(interaction) {
  return createDiscoreEmbed(interaction, {
    title: "🔀 Merging Scoreboards — Full Guide",
    description: [
      "> ⚠️ Merge is a **Premium feature**.",
      "",
      "### What Is Merging?",
      "Merging copies scores from a **source** scoreboard into a **target** (totals) scoreboard.",
      "",
      "This lets you:",
      "• Combine seasonal boards into a permanent totals board",
      "• Track cumulative stats over time",
      "• Reuse the same live boards season after season",
      "• View everything together or by source",
      "",
      "### 🔀 Merge Command",
      "`/scoreboard merge` takes three options:",
      "• **merging_board** — The source board being merged (scores copied FROM here)",
      "• **base_board** — The target board receiving the scores",
      "• **after_merge** — What happens to the source after merge",
      "",
      "### 🗜️ Merge Options",
      "",
      "**1. 📦 Archive (Recommended)**  `merge_archive`",
      "• Scores are copied into the target",
      "• Source board is archived (removed from active list but preserved)",
      "• Can be restored later",
      "",
      "**2. 🧹 Clear & Keep Live**  `merge_clear_keep_live`",
      "• Scores are copied into the target",
      "• Source board is **cleared** (all entries removed)",
      "• Source board stays **live** and **reusable** for new scores",
      "• Live embed resets to empty — ready for the next season",
      "• ⏱️ Live embeds may take up to 10 minutes to fully update",
      "",
      "**3. 📋 Keep Live & Keep Scores**  `merge_keep_live_keep_scores`",
      "• Scores are copied into the target",
      "• Source board stays live with its scores unchanged",
      "• Useful for copying into a totals board without affecting the original",
      "",
      "**4. 🗑️ Delete**  `merge_delete`",
      "• Scores are copied into the target",
      "• Source board is **permanently deleted** from the database",
      "• ⚠️ This cannot be undone — prefer archive unless you're sure",
      "",
      "### 📂 How Categories Work in Totals",
      "When you merge source boards into a totals board:",
      "",
      "• **First merge** — Scores appear flat in the totals board (no visible categories yet)",
      "• **Second merge** — Totals switches to category mode. Each source becomes a category.",
      "• **Re-merging the same source later** — Scores add into the **existing** category (no duplicates)",
      "• **Each new source** — Creates its own category",
      "",
      "Example:",
      "```",
      "Season 1: Merge 'WW3 4x' into 'Totals' → Flat display",
      "Season 2: Merge 'WW3 1x' into 'Totals' → Now has 2 categories",
      "Season 3: Merge 'WW3 4x' again → Adds to existing 'WW3 4x' category",
      "```",
      "",
      "### 📏 Score Combination Rules",
      "During merge:",
      "• **Same target in same category** → Scores combine (additive)",
      "• **Different targets** → New entries are created",
      '• **Same target in different categories** → Stored separately; only combined in "All Scores Combined" view',
    ].join("\n"),
  });
}

async function buildArchiveEmbed(interaction) {
  return createDiscoreEmbed(interaction, {
    title: "🗄️ Archives — Full Guide",
    description: [
      "> ⚠️ Archives are a **Premium feature**.",
      "",
      "### What Is Archiving?",
      "Archiving preserves a scoreboard's data without deleting it or leaving it live — archived boards don't count toward your live scoreboard limit.",
      "",
      "### 🗄️ Archive Commands",
      "All archive management is under `/archive`:",
      "",
      "**`/archive list`** — Browse archived scoreboards with pagination",
      "• Optional filter by month (`YYYY-MM`) or search query",
      "",
      "**`/archive search`** — Search archived scoreboards by name, ID, or text",
      "",
      "**`/archive view`** — View an archived scoreboard by its archive ID (e.g. `A-202606-001`)",
      "",
      "**`/archive restore`** — Restore an archive as a new live scoreboard",
      "• Optionally give the restored board a new name",
      "",
      "**`/archive add-result`** — Add a win, loss, or points to an archived scoreboard",
      "• Useful for late corrections without restoring the whole board",
      "",
      "### 🔀 Archiving via Merge",
      "Boards also get archived automatically when merged with the **Archive** option — see the **Merging Scoreboards** section for details.",
    ].join("\n"),
  });
}

async function buildModerationEmbed(interaction) {
  return createDiscoreEmbed(interaction, {
    title: "🛡️ Moderation — Command Guide",
    description: [
      "> ⚠️ This system is **in active development**. Behaviour may change.",
      "",
      "### 🔨 Mod Commands",
      "All mod actions are under `/mod`:",
      "",
      "**`/mod warn`** — Issue a formal warning",
      "• Requires: **Moderate Members** permission",
      "• Creates a case record visible to the warned user",
      "",
      "**`/mod mute`** — Mute a user (Discore managed mute role)",
      "• Requires: **Moderate Members** permission",
      "• Optional duration: `30m`, `1 hour`, `7 days`, etc.",
      "• Auto-expires when duration ends",
      "",
      "**`/mod timeout`** — Discord native timeout",
      "• Requires: **Moderate Members** permission",
      "• Duration is required (up to 28 days Discord limit)",
      "",
      "**`/mod ban`** — Ban a user from the server",
      "• Requires: **Moderate Members** permission",
      "• Optional duration for temp bans",
      "• Optional message deletion: 0-7 days",
      "",
      "**`/mod unban`** — Unban a previously banned user",
      "• Provide user ID (not mention, since they're not in the server)",
      "",
      "**`/mod probation`** — Place a user on probation",
      "• Visible on their public player profile",
      "• Duration is required",
      "",
      "### 📋 Case Management",
      "**`/mod case MOD-XXXXX`** — View a specific moderation case by ID",
      "• Public command — anyone can look up a case",
      "• Shows action type, reason, moderator, duration, and status",
      "• Revoked/cleared cases are hidden from public view",
      "",
      "**`/mod cases @user`** — List all cases for a user",
      "• Shows case IDs, actions, and dates",
      "",
      "**`/mod revoke MOD-XXXXX`** — Revoke/overturn a moderation action",
      "• Requires: **Moderate Members** permission",
      "• Removes the case from public record",
      "",
      "### 🎫 Appeals System",
      "Appeals allow users to contest moderation actions:",
      "• Appeals are filed from cases and tracked in dedicated channels",
      "• Appeal channels and categories are configured in server setup",
      "• Staff can accept, reject, or reduce penalties through the appeal system",
      "• Appealed cases show their appeal status on the case embed",
      "",
      "### 🛡️ Automod",
      "Configure automatic phrase-based moderation with `/automod`:",
      "• Match types: Exact, Contains, Starts With, Regex",
      "• Actions: Delete message, send to review, mute, or timeout",
      "",
      "### 🔑 Required Permissions",
      "• Most mod actions require the **Moderate Members** Discord permission",
      "• Some features use the **Scoreboard Manager** role or **Manage Server** permission",
    ].join("\n"),
  });
}

async function buildEventsEmbed(interaction) {
  return createDiscoreEmbed(interaction, {
    title: "🎮 Events & Battles — Command Guide",
    description: [
      "> ⚠️ This system is **in active development**. Behaviour may change.",
      "",
      "### 📅 Event Control Centre",
      "Run **`/event`** to open the **Event Control Centre** — a premium interactive dashboard.",
      "",
      "**Dashboard buttons:**",
      "• **➕ Create Event** — Start the 6-step event creation wizard",
      "• **📋 View Events** — See upcoming and live events with RSVP counts",
      "• **🔄 Refresh** — Reload the dashboard",
      "• **❌ Close** — Close the dashboard",
      "",
      "### 🧙 Event Creation Wizard",
      "The wizard guides you through 6 simple steps:",
      "",
      "**Step 1 — Event Type:**",
      "Pick a type: Event, Game Sign-On, Team, Community, Training, Game Start, or Custom.",
      "",
      "**Step 2 — Basic Info:**",
      "Fill in title, date/time, description, location, and game via a modal.",
      "",
      "**Step 3 — Type Settings:**",
      "• For **Game Sign-On**: Set team size (slots per side).",
      "• For **Custom**: Set a custom event label (e.g. Movie Night).",
      "• Other types: No extra settings needed.",
      "",
      "**Step 4 — Pings & Reminders:**",
      "• Select up to 3 ping roles",
      "• Toggle ping on post and ping on start",
      "• Set a channel reminder (10min to 24h before start)",
      "• Set auto-delete (1h to 7 days after start)",
      "",
      "**Step 5 — Style & Images:**",
      "• Pick an embed colour (or custom hex)",
      "• Upload a **thumbnail** (small top-right image)",
      "• Upload a **banner** (full-width bottom image)",
      "• Images are uploaded directly from your device via Discord file picker",
      "",
      "**Step 6 — Preview & Post:**",
      "• Review all event details",
      "• Click **Post Event** to post to the current channel",
      "• Or click **Save Draft** to save as a draft (auto-cleaned after 24h)",
      "",
      "### 💾 Drafts & Cleanup",
      "• Drafts auto-delete after 24 hours if never posted",
      "• Posted events clean up from Discore's database 7 days after the event ends",
      "• The Discord embed stays visible unless you set auto-delete",
      "• Cancelled events are removed from the database immediately",
      "",
      "### 🔧 Advanced / Existing Features",
      "• RSVP system: Going, Maybe, Not Going",
      "• Role pings on creation and start",
      '• Personal reminders via the "Remind Me" button',
      "• `/event show` and `/event list` still available for quick access",
    ].join("\n"),
  });
}

async function buildPlayersEmbed(interaction) {
  return createDiscoreEmbed(interaction, {
    title: "👤 Players & Alliances — Command Guide",
    description: [
      "> ⚠️ This system is **in active development**. Behaviour may change.",
      "",
      "### 👤 Player Profiles",
      "Manage your player identity with `/player`:",
      "• Link your in-game profile to Discord",
      "• Track stats: K/D, rank, victories, ELO",
      "• Alliance history tracking across games",
      "• Performance scores and combat style",
      "• Public/private profile toggle",
      "• Screenshot and profile image uploads",
    ].join("\n"),
  });
}

async function buildPremiumEmbed(interaction) {
  return createDiscoreEmbed(interaction, {
    title: "⭐ Premium & Server Setup",
    description: [
      "> ⚠️ Features and limits are **subject to change** during development.",
      "",
      "### 🎖️ Plans",
      "",
      "**FREE** — Basic access",
      "• 5 live scoreboards maximum",
      "• 5 live events maximum",
      "• Basic game data lookups",
      "• Player & alliance profiles",
      "• Suggestions",
      "",
      "**Discore Premium** — one plan, everything included",
      "• 50 live scoreboards",
      "• 50 live events",
      "• Scoreboard archive & merge",
      "• Custom bot nickname & footer",
      "• 2,000 AI credits included monthly",
      "",
      "**LIFETIME** — special one-time grant (codes/giveaways, not directly purchasable)",
      "• 999 live scoreboards",
      "• 9,999 live events",
      "• All Premium features",
      "• 5,000 AI credits monthly",
      "",
      "### 🤖 AI Credits",
      "AI (`/ask`, translation, welcome messages) runs on **credits**, separate from Premium:",
      "• Any server can buy a 3,000-credit pack via `/premium` → **Buy AI Credits** — no Premium required",
      "• Premium servers get 2,000 credits/month automatically, on top of any purchased packs",
      "• Credits are consumed only on a successful AI response",
      "",
      "### 🛠️ Server Setup",
      "Configure your server with `/server`:",
      "• `/server setup` — Initial server configuration wizard",
      "• `/server branding` — Set alliance name, logo, theme colour",
      "• `/server timezone` — Set server timezone for event scheduling",
      "• `/server default-game` — Set the default game for commands",
      "• `/server channels` — Configure scoreboard, event, log, and moderation channels",
      "",
      "### 💳 Premium Management",
      "`/premium` — View status, plan, and AI credit balance, then use the buttons to:",
      "• Upgrade / Manage Premium (via Discord's Server Apps subscription)",
      "• Buy AI Credits (one-time 3,000-credit pack)",
      "• Refresh Status",
      "• AI Usage Limits & Feature Toggles (server daily limit, per-user limit, cooldown)",
      "• Usage Details",
      "",
      "### 📏 Free Limits — Quick Reference",
      "• **5 live scoreboards** maximum",
      "• Cannot use archive system",
      "• Cannot use merge system",
      "• Cannot use custom nickname/footer",
      "• AI still works if the server has purchased AI credits",
      "",
      "### ⚠️ Important Notes",
      "• Limits apply to the **entire server**, not per user",
      "• Free servers who try to create a 6th live scoreboard will be blocked",
      "• Premium is server-based: one activation covers the whole server",
      "• AI credits are also server-based, shared by everyone in the server",
      "",
      "### 💰 How to Upgrade",
      "Run `/premium` and click a button — both open Discord's built-in **Server Shop**, where our two packages are sold securely through Discord (no external site or card details needed):",
      "• **Upgrade / Manage Premium** — subscribe to Discore Premium",
      "• **Buy AI Credits** — buy a one-time 3,000-credit pack",
    ].join("\n"),
  });
}

async function buildAutoPostsEmbed(interaction) {
  return createDiscoreEmbed(interaction, {
    title: "📣 Auto Posts & Welcome — Complete Guide",
    description: [
      "> ⚠️ Auto Posts are a **Premium feature**.",
      "",
      "### 🔰 What Are Auto Posts?",
      "Auto Posts let you automate messages in your server based on triggers. Create scheduled announcements, welcome messages for new members, mention-triggered replies, and keyword-based auto-responses.",
      "",
      "### 🚀 Getting Started",
      "Run **`/autopost`** to open the **Auto Post Dashboard** — a premium interactive panel.",
      "",
      "**Dashboard buttons:**",
      "• **➕ Create** — Start the step-by-step creation wizard",
      "• **📋 List** — View all your auto posts with status",
      "• **✏️ Edit** — Edit existing auto post content or channel",
      "• **⏸️ Pause/Resume** — Toggle posts on or off",
      "• **🗑️ Delete** — Remove a post permanently",
      "• **🧪 Test Send** — Preview a post before going live",
      "• **🔄 Refresh** — Reload the dashboard",
      "• **❓ Help / Guide** — Quick reference inside the panel",
      "• **📝 View Placeholders** — Full placeholder reference",
      "",
      "### 📋 Trigger Types",
      "",
      "**⏰ Scheduled** — Send at specific times",
      "• Recurrence: once, daily, weekly, monthly, or every X hours",
      "• Set time (HH:MM) and timezone",
      "• Perfect for: daily reminders, weekly announcements, monthly recaps",
      "",
      "**👋 Member Join** — Welcome new members automatically",
      "• Sends when a new member joins your server",
      '• Includes a Yes/No toggle: "Send member join message to new arrival?"',
      "• Supports member-specific placeholders like `{user_mention}` and `{display_name}`",
      "• Safely pings only the joining user — no @everyone abuse",
      "",
      "**💬 Mention Trigger** — Reply when a role/user is mentioned",
      "• Configure a role ID or user ID to watch for",
      "• Set a cooldown to prevent spam (30–86400 seconds)",
      "",
      "**🔑 Keyword/Phrase** — Reply when text appears in chat",
      "• Match type: CONTAINS or EXACT",
      "• Set a cooldown to prevent spam",
      "",
      "### 📝 All Supported Placeholders",
      "Use these `{placeholder}` tags in your message content, embed title, embed description, and footer. They are automatically replaced when the post is sent:",
      "",
      "| Placeholder | Replaces With |",
      "|---|---|",
      "| `{user_mention}` | Discord ping for the joining user (e.g. @User) |",
      "| `{user}` | Alias for `{user_mention}` |",
      "| `{user_id}` | Joining user's Discord ID |",
      "| `{username}` | Discord username |",
      "| `{display_name}` | Display name / nickname in this server |",
      "| `{server_name}` | Server name |",
      "| `{member_count}` | Current member count |",
      "| `{join_date}` | Formatted join date/time |",
      "| `{date}` | Current date |",
      "| `{time}` | Current time |",
      "| `{channel}` | Target channel mention |",
      "| `{trigger}` | Trigger type label |",
      "",
      "**Legacy camelCase aliases** also work: `{serverName}`, `{memberCount}`, `{userMention}`, `{displayName}`",
      "",
      "**Channel mention format:** `<#channel_id>` (Discord renders it as a clickable channel)",
      "**Role mention format:** `<@&role_id>`",
      "**User mention (member join):** Handled by `{user_mention}`",
      "",
      "### 📝 Full Welcome Template Example",
      "Here is a complete example of a member-join welcome post:",
      "",
      '**Message Mode:** "Message + Embed" (BOTH)',
      "",
      "**Message Content:**",
      "```",
      "👋 Welcome {user_mention}!",
      "```",
      "",
      "**Embed Title:**",
      "```",
      "🛡️ Welcome to The Last Battalion, {display_name}!",
      "```",
      "",
      "**Embed Description:**",
      "```",
      "Welcome aboard, and thank you for joining **{server_name}**! ⚔️🔥",
      "",
      "Before you get full access, please complete your application here:",
      "👉 <#1516162309456789735>",
      "",
      "Also, make sure you select your roles here:",
      "👉 <#1516199241251422279>",
      "",
      "Once that's done, say hello, look around, and get settled in.",
      "Welcome to **{server_name}** — glad to have you with us. 🐺🛡️",
      "```",
      "",
      "**Embed Footer:**",
      "```",
      "Discore Auto Post • Member Welcome | Member #{member_count}",
      "```",
      "",
      "### 👋 Member Join Settings",
      "When creating a Member Join auto post, after filling in content you'll see the **Member Join Settings** panel:",
      "",
      "**Send member join message to new arrival?**",
      "• **✅ Yes** — Send this welcome message when a member joins (default)",
      "• **❌ No** — Keep this saved but do not send it automatically",
      "",
      "You can toggle this anytime by editing the post.",
      "",
      "### 🛡️ Safety Features",
      "• Auto post messages **never** ping `@everyone` or `@here`",
      "• Cooldowns prevent spam (default: 5 minutes for triggers)",
      "• Bot messages and self-posts are ignored",
      "• Auto-pauses after 3 consecutive send failures",
      "• `allowed_mentions` is locked down: only the joining user can be pinged",
      "• Test sends / previews never ping real users",
      "",
      "### 💡 Tips",
      "• Use **BOTH** mode to send a ping in message content + rich info in the embed",
      "• Put `{user_mention}` in the **message content** (not just the embed title) for a real ping notification",
      "• Use `<#channel_id>` in descriptions for clickable channel links",
      "• Click **📝 View Placeholders** in the dashboard anytime for a quick reference",
      "• Use **🧪 Test Send** to preview how your post will actually look",
      "",
      "### ⚠️ Limits",
      "• Max 5 auto posts per server",
      "• Premium-only feature",
      "• Message content: 1,900 characters max",
      "• Embed title: 256 characters max",
      "• Embed description: 4,000 characters max",
      "• Footer: 2,048 characters max",
    ].join("\n"),
  });
}

async function buildXpEmbed(interaction) {
  return createDiscoreEmbed(interaction, {
    title: "✨ XP & Leveling — Complete Guide",
    description: [
      "> ⚠️ This system is **in active development**. Behaviour may change.",
      "",
      "### 🎯 What Is Discore XP?",
      "Discore XP is an activity-based leveling system that rewards members for chatting and engaging in your server. Think Arcane/MEE6-style XP but built directly into Discore with premium polish.",
      "",
      "### 📈 How It Works",
      "• **Message XP** — Send messages in any channel to earn XP (FREE)",
      "• **Reaction XP** — Add reactions to earn small bonus XP (Premium)",
      "• **Cooldowns** — Prevents spam farming. Default 60s for messages, 300s for reactions",
      "• **Level-ups** — Announced in your configured level-up channel with a premium gold card",
      "",
      "### 📊 Viewing Your Stats",
      "**`/xp rank`** — View your current level, XP, progress, and rank",
      "• Shows a beautiful gold profile card with all your stats",
      "• Also viewable inside `/player profile`",
      "",
      "**`/xp leaderboard`** — View the server XP leaderboard",
      "• 📊 **Overall** — All-time XP rankings",
      "• 📅 **Daily** — Today's most active members",
      "• 🗓️ **Weekly** — This week's top earners",
      "• 🌙 **Monthly** — This month's XP leaders",
      "",
      "### ⚙️ Setting Up XP (Admins)",
      "Run **`/xp setup`** to open the **XP Control Panel** — a premium interactive panel with buttons and modals:",
      "",
      "**⚙️ General** — Enable/disable the XP system, message XP, reaction XP, level-up announcements, and weekly top 10 posts",
      "",
      "**🎁 XP Rewards** — Set the XP range per message (default 15–40) and per reaction (default 5–10)",
      "",
      "**⏱️ Cooldowns** — Control how often members can earn XP. Message cooldown (default 60s) and reaction cooldown (default 300s)",
      "",
      "**📣 Channels** — Set where level-up announcements and weekly leaderboard posts go",
      "",
      "**🧪 Preview** — Test your profile card, level-up card, and weekly top 10 without earning XP",
      "",
      "**🛠️ Admin Tools** — Reset individual user XP, wipe the entire server's XP, or reset weekly/monthly counters",
      "",
      "### 🔢 XP Formula",
      "Discore uses a simple increasing curve:",
      "• Level 1 → 0 XP",
      "• Level 2 → 100 XP total",
      "• Level 3 → 300 XP total",
      "• Level 4 → 600 XP total",
      "• Level n → 50 × n × (n−1) XP total",
      "",
      "This keeps early levels fast and rewarding while making higher levels progressively harder.",
      "",
      "### 🎨 Profile & Level-Up Cards",
      "Discore generates **premium gold-themed image cards** for:",
      "• **Level-ups** — Sent to your level-up channel with user @mention",
      "• **Profile cards** — Shown in `/xp rank` and `/player profile`",
      "• Cards include your avatar, display name, level, XP bar, rank, period XP, activity stats, and account info",
      "",
      "### 🗑️ Wiping XP Data",
      "Admins can reset XP data through the **Admin Tools** in `/xp setup`:",
      "• **Reset User XP** — Wipe a single user's XP (by user ID)",
      "• **Wipe Server XP** — Reset **all** XP for the entire server (requires typed confirmation: `RESET SERVER XP`)",
      "• **Reset Weekly XP** — Clear only this week's XP counters (keeps total XP and levels)",
      "• **Reset Monthly XP** — Clear only this month's XP counters",
      "",
      "### 🏆 Weekly Top 10",
      "If enabled, Discore automatically posts a **Weekly XP Top 10** leaderboard to your configured channel every Sunday.",
      "",
      "### 💎 Free vs Premium",
      "| Feature | Free | Premium |",
      "|---|---|---|",
      "| Message XP | ✅ | ✅ |",
      "| Reaction XP | ❌ | ✅ |",
      "| `/xp rank` & leaderboard | ✅ | ✅ |",
      "| Level-up announcements | ✅ | ✅ |",
      "| Weekly Top 10 auto-post | ❌ | ✅ |",
      "| Profile cosmetics (future) | ❌ | ✅ |",
      "",
      "### 📝 Commands Quick Reference",
      "`/xp setup` — Open the XP Control Panel (admin)",
      "`/xp rank` — View your XP stats",
      "`/xp leaderboard` — View server leaderboard",
      "`/xp wipe` — Quick wipe of server/user XP (admin)",
      "`/player profile` — View profile including XP section",
    ].join("\n"),
  });
}

// ─── Get embed builder ────────────────────────────────────────────────────────

async function getCategoryEmbed(interaction, category) {
  switch (category) {
    case "overview":
      return buildOverviewEmbed(interaction);
    case "scoreboards":
      return buildScoreboardsEmbed(interaction);
    case "merge":
      return buildMergeEmbed(interaction);
    case "archive":
      return buildArchiveEmbed(interaction);
    case "moderation":
      return buildModerationEmbed(interaction);
    case "events":
      return buildEventsEmbed(interaction);
    case "players":
      return buildPlayersEmbed(interaction);
    case "premium":
      return buildPremiumEmbed(interaction);
    case "xp":
      return buildXpEmbed(interaction);
    case "autoposts":
      return buildAutoPostsEmbed(interaction);
    default:
      return buildOverviewEmbed(interaction);
  }
}

// ─── Build updated select menu for the chosen category ───────────────────────

function buildHelpSelectMenu(currentCategory) {
  const { StringSelectMenuBuilder } = require("discord.js");

  const options = CATEGORIES.map((cat) =>
    new StringSelectMenuOptionBuilder()
      .setLabel(`${cat.emoji} ${cat.label}`)
      .setDescription(cat.description)
      .setValue(cat.value)
      .setDefault(cat.value === currentCategory),
  );

  return new ActionRowBuilder().addComponents(
    new StringSelectMenuBuilder()
      .setCustomId("help:category:")
      .setPlaceholder("Select a help category...")
      .addOptions(options),
  );
}

function buildSupportButtonRow() {
  const { ButtonBuilder, ButtonStyle } = require("discord.js");
  return new ActionRowBuilder().addComponents(
    new ButtonBuilder()
      .setCustomId("help:support")
      .setLabel("Need help? Have a suggestion or bug to report?")
      .setEmoji("🆘")
      .setStyle(ButtonStyle.Secondary),
  );
}

const { ActionRowBuilder } = require("discord.js");

// ─── Component handler ───────────────────────────────────────────────────────

module.exports = {
  customIdPrefix: "help:category:",
  async execute(interaction) {
    const category = interaction.values[0];
    const embed = await getCategoryEmbed(interaction, category);
    const selectRow = buildHelpSelectMenu(category);

    await interaction.update({
      embeds: [embed],
      components: [selectRow, buildSupportButtonRow()],
    });
  },
};
