-- Premium V3: AI credit tracking, Discord entitlements, usage limits
ALTER TABLE "GuildPremium"
ADD COLUMN IF NOT EXISTS "entitlementId" TEXT,
ADD COLUMN IF NOT EXISTS "monthlyAiAllowance" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS "monthlyAiUsed" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS "monthlyAiPeriodStart" TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS "monthlyAiPeriodEnd" TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS "extraAiCredits" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS "serverDailyAiLimit" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS "perUserDailyAiLimit" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS "cooldownSeconds" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS "aiEnabled" BOOLEAN NOT NULL DEFAULT true;

CREATE TABLE IF NOT EXISTS "ProcessedEntitlement" (
  "id" TEXT NOT NULL,
  "guildId" TEXT NOT NULL,
  "skuId" TEXT NOT NULL,
  "entitlementId" TEXT NOT NULL,
  "creditsGranted" INTEGER NOT NULL DEFAULT 0,
  "processedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT "ProcessedEntitlement_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "ProcessedEntitlement_entitlementId_key" UNIQUE ("entitlementId")
);