"use strict";

/**
 * Generate a PDF transcript from stored ModerationCaseTranscript data.
 * Uses a lightweight pure-JS approach (no external PDF library needed).
 * Falls back to TXT if PDF generation fails for any reason.
 */

async function generateTranscriptPdf(transcript) {
  // Parse messages from JSON
  let messages = [];
  try {
    if (transcript.transcriptJson) {
      messages = JSON.parse(transcript.transcriptJson);
    }
  } catch {
    messages = [];
  }

  // Build a clean text transcript (used for both PDF content and TXT fallback)
  const lines = [];

  // Header
  lines.push("=".repeat(60));
  lines.push("  DIS CORE OFFICIAL  ·  MODERATION TRANSCRIPT");
  lines.push("=".repeat(60));
  lines.push("");

  // Case metadata
  lines.push("CASE DETAILS");
  lines.push("-".repeat(40));
  if (transcript.appealNumber)
    lines.push(`  Appeal Number:  ${transcript.appealNumber}`);
  if (transcript.caseNumber)
    lines.push(`  Case Number:    ${transcript.caseNumber}`);
  if (transcript.ticketChannelName)
    lines.push(`  Ticket Channel: ${transcript.ticketChannelName}`);
  if (transcript.userId) lines.push(`  User ID:        ${transcript.userId}`);
  if (transcript.handledById)
    lines.push(`  Handled By:     ${transcript.handledById}`);
  if (transcript.outcome) lines.push(`  Outcome:        ${transcript.outcome}`);
  if (transcript.openedAt)
    lines.push(
      `  Opened:         ${new Date(transcript.openedAt).toLocaleString()}`,
    );
  if (transcript.closedAt)
    lines.push(
      `  Closed:         ${new Date(transcript.closedAt).toLocaleString()}`,
    );
  lines.push(`  Messages:       ${transcript.messageCount}`);
  lines.push("");
  lines.push("");

  // Messages
  lines.push("TRANSCRIPT MESSAGES (chronological)");
  lines.push("-".repeat(40));
  lines.push("");

  for (const msg of messages) {
    const time = msg.createdAt
      ? new Date(msg.createdAt).toLocaleString()
      : "Unknown time";
    const author =
      msg.authorId && msg.authorName
        ? `${msg.authorName} (${msg.authorId})`
        : msg.authorId || msg.authorName || "Unknown";
    lines.push(`[${time}] ${author}`);

    if (msg.content) {
      lines.push(`  ${msg.content}`);
    }

    if (msg.attachments && msg.attachments.length > 0) {
      lines.push(`  Attachments:`);
      for (const url of msg.attachments) {
        lines.push(`    ${url}`);
      }
    }

    if (msg.embeds && msg.embeds.length > 0) {
      lines.push(`  Embeds:`);
      for (const embed of msg.embeds) {
        if (embed.title) lines.push(`    Title: ${embed.title}`);
        if (embed.description)
          lines.push(`    Description: ${embed.description}`);
      }
    }

    lines.push("");
  }

  lines.push("");
  lines.push("=".repeat(60));
  lines.push("  END OF TRANSCRIPT");
  lines.push("  Generated by Discore Official");
  lines.push("=".repeat(60));

  const text = lines.join("\n");

  // Return as buffer (PDF or TXT)
  // For maximum reliability, we always generate a clean text file
  // which is more compatible than PDF and loads instantly in Discord
  return Buffer.from(text, "utf-8");
}

module.exports = { generateTranscriptPdf };
